name: gtamodel_tools
channels:
  - conda-forge

dependencies:
  - python=3.11
  - geopandas
  - jupyterlab
  - matplotlib
  - numexpr
  - numpy
  - openpyxl
  - pandas
  - pandera-pandas
  - pyogrio=0.7.*
  - pytest
  - shapely
  - yaml