
# Toronto Centreline Shapefile 
TCL_INDEX = 'CENTRELINE_ID'
TCL_RDCLS_COL = 'FEATURE_CODE_DESC'
TCL_ONEWAYCODE_COL = 'ONEWAY_DIR_CODE'
TCL_FROM_INTSC = 'FROM_INTERSECTION_ID'
TCL_TO_INTSC = 'TO_INTERSECTION_ID'

CLASSES_FREEWAY = ['Expressway', 'Expressway Ramp']
CLASSES_ARTERIAL = ['Major Arterial', 'Minor Arterial', 
                    'Major Arterial Ramp', 'Minor Arterial Ramp']
CLASSES_COLLECTOR = ['Collector', 'Collector Ramp']
CLASSES_LOCAL = ['Local']
CLASSES_SERVICE = ['Laneway', 'Access Road']
CLASSES_TRANSIT = ['Busway']
CLASSES_ACTIVE = ['Walkway', 'Trail']

CLASSES_ROAD = CLASSES_FREEWAY + CLASSES_ARTERIAL + CLASSES_COLLECTOR \
    + CLASSES_LOCAL + CLASSES_SERVICE + CLASSES_TRANSIT
CLASSES_TRANSPORT = CLASSES_ROAD + CLASSES_ACTIVE

# Toronto Centreline Intersection
INTSC_INDEX = 'INTERSECTION_ID'
